# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-03 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190803_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(default='DEFAULT VALUE', upload_to='images/'),
        ),
    ]
